### ISSUE TITLE
Cant save on Legend of Zeld Links awakening

### ISSUE THREAD

**Issue by EILMaxO** [deltabeard/Peanut-GB#100]
Apparently your supposed to press A + B + select + start, but when I try that it brings me back to the game selection menu if someone can help it will be very appreciated, thanks.

**Comment by deltabeard** [comment]
I haven't had this problem with Links Awakening. Is this the original or the DX version? I'll test again later.

**Comment by Takiiiiiiii** [comment]
This is the original and it is due to select and start being used as a menu hotkey in Pico-GB.

**Comment by deltabeard** [comment]
That's an issue with Pico-GB, not the emulator Peanut-GB itself. The relevant code is at https://github.com/YouMakeTech/Pico-GB/blob/efc56e55e12ec425e9ce8835809965a54116a4d8/src/main.c#L760. The code could be changed to a different button combination, or require pressing and holding start+select for a few seconds instead, for example.
