### ISSUE TITLE
Black box when falling in hole in Libbet and the Magic Floor

### ISSUE THREAD

**Issue by pinobatch** [deltabeard/Peanut-GB#35]
If bit 7 of [a sprite's attributes](https://gbdev.gg8.se/wiki/articles/Video_Display#Byte3_-_Attributes.2FFlags:) ($FE03, $FE07, $FE0B, ..., $FE9F) is true, the sprite's pixels are supposed to be drawn behind any background pixels that are not color 0. The comparison with color 0 is supposed to happen before BGP is applied.

To reproduce:
1. Open [_Libbet and the Magic Floor_ v0.04](https://github.com/pinobatch/libbet/releases/tag/v0.04)
2. Press Select to start the demo
3. Wait for Libbet to roll to the dead end at the top right corner

Expect: Libbet smoothly falls into the hole

Actual: A black square appears on the white cell below Libbet, which would otherwise have been hidden behind the background.

**Comment by deltabeard** [comment]
Fixed in 878bc90a9766cfef5cb57ba64b8a0269a20bc326.

![LIBBET](https://user-images.githubusercontent.com/3747104/208778565-b877bc11-9b32-4c08-bb2f-0d25f65d52ce.gif)
