### ISSUE TITLE
core: serial code interfering with incompatible games

### ISSUE THREAD

**Issue by itsmeitsme** [deltabeard/Peanut-GB#39]
Hi, 
after quite some debugging I found out that Tetris won't work as long as the serial support is enabled. If you remove the serial interrupt and transfer code, Tetris will fully work again.

However, I haven't figured out the exact cause.

**Comment by deltabeard** [comment]
Thanks! This should be fixed now. I also tested this with Pokemon Yellow.
Serial won't work right now due to lack of implementing external and internal clocks I think. I'll have a proper look at making serial working in the future.
