### ISSUE TITLE
selected_rom_bank should be uint16_t?

### ISSUE THREAD

**Issue by Ryzee119** [deltabeard/Peanut-GB#48]
Defined here:
https://github.com/deltabeard/Peanut-GB/blob/bf98d5b1297196962be9117d56689aae829e2732/peanut_gb.h#L394

MBC5 uses a 9th bit for ROM banking.

Currently code like this wont work as expected:
https://github.com/deltabeard/Peanut-GB/blob/bf98d5b1297196962be9117d56689aae829e2732/peanut_gb.h#L761

**Comment by deltabeard** [comment]
Thank you!
